### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by JACKYLUO1991** [chaofengc/Face-Sketch-SCG#1]
您好，我尝试了一下您的代码库，然而训练时间过长，请问有什么优化的方法吗？

**Comment by chaofengc** [comment]
代码里的训练时间不是必须的，可以early stop

**Comment by JACKYLUO1991** [comment]
@chaofengc 然而，这上面显示TimeLeft 40 days，未免有点恐怖....

**Comment by chaofengc** [comment]
log的训练时间是通过`--n_epochs`参数来估计的，并没有实际的参考价值。
我们通过validation的performance做early stop。
需要的话，您可以调整该参数估计训练时间。

在1080Ti上的训练时间大概在2~3天左右。

**Comment by JACKYLUO1991** [comment]
@chaofengc 再次打扰，能否给出如何从已有训练的断点继续训练的提示呢？

**Comment by chaofengc** [comment]
我们只提供简单的resume功能，通过以下两个参数实现:

https://github.com/chaofengc/Face-Sketch-SCG/blob/de9cd7b219224634efbb198a600c5f9c2b760875/models/semicycle_gan_model.py#L40-L41

您需要自己写代码去resume完整的训练状态

**Comment by JACKYLUO1991** [comment]
@chaofengc 已成功实现断点继续训练功能，多谢多谢！
